"""test of fixd

Revision ID: a2572cda6f2c
Revises: 8b41688683b8
Create Date: 2024-08-23 20:25:48.744636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2572cda6f2c'
down_revision: Union[str, None] = '8b41688683b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255, collation='Japanese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('deadline', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=10, collation='Japanese_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__todos__3213E83FE273C39E')
    )
    # ### end Alembic commands ###
