"""Test Base.metadata change.

Revision ID: 8b41688683b8
Revises: bb1ee83f48eb
Create Date: 2024-07-28 20:24:34.690204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b41688683b8'
down_revision: Union[str, None] = 'bb1ee83f48eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
