"""empty message

Revision ID: 3276d5a05fb0
Revises: fd55cbb71fad
Create Date: 2024-09-16 21:44:16.161734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3276d5a05fb0'
down_revision = 'fd55cbb71fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
